
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ForgeConfig : Luban.BeanBase
    {
        public ForgeConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); ItemIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ItemIds.Add(_e0);}}
            {int n0 = _buf.ReadSize(); GetItemIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); GetItemIds.Add(_e0);}}
            Name = _buf.ReadString();
            {int n0 = _buf.ReadSize(); MiniEnterLevel = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); MiniEnterLevel.Add(_e0);}}
            PrefabName = _buf.ReadString();

            EndInit();
        }

        public static ForgeConfig DeserializeForgeConfig(ByteBuf _buf)
        {
            return new ForgeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 配方列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ItemIds;
        /// <summary>
        /// 生成列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> GetItemIds;
        /// <summary>
        /// 关卡名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 准入等级范围
        /// </summary>
        public readonly System.Collections.Generic.List<int> MiniEnterLevel;
        /// <summary>
        /// 预设物名
        /// </summary>
        public readonly string PrefabName;
    
        public const int __ID__ = -873645719;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ItemIds:" + Luban.StringUtil.CollectionToString(ItemIds) + ","
            + "GetItemIds:" + Luban.StringUtil.CollectionToString(GetItemIds) + ","
            + "Name:" + Name + ","
            + "MiniEnterLevel:" + Luban.StringUtil.CollectionToString(MiniEnterLevel) + ","
            + "PrefabName:" + PrefabName + ","
            + "}";
        }

        partial void EndRef();
    }

}

