
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class ForgeConfigCategory : Singleton<ForgeConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, ForgeConfig> _dataMap;
        private readonly List<ForgeConfig> _dataList;
        
        public ForgeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ForgeConfig>();
            _dataList = new List<ForgeConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ForgeConfig _v;
                _v = global::ET.ForgeConfig.DeserializeForgeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ForgeConfig> GetAll() => _dataMap;
        public Dictionary<int, ForgeConfig> DataMap => _dataMap;
        public List<ForgeConfig> DataList => _dataList;

        public ForgeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ForgeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

