
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TalismanConfig : Luban.BeanBase
    {
        public TalismanConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Type = _buf.ReadInt();
            EquipPosition = _buf.ReadInt();
            Icon = _buf.ReadString();
            Shape = _buf.ReadInt();
            Weight = _buf.ReadInt();
            MaxSumCount = _buf.ReadInt();
            Rarity = _buf.ReadInt();
            SellBasePrice = _buf.ReadInt();
            BaseScore = _buf.ReadInt();
            LabelType = _buf.ReadInt();
            Element = _buf.ReadInt();
            Huo = _buf.ReadInt();
            Shui = _buf.ReadInt();
            Bing = _buf.ReadInt();
            Lei = _buf.ReadInt();
            Feng = _buf.ReadInt();
            AddBuff = _buf.ReadInt();
            TimeBuff = _buf.ReadInt();
            MultBuff = _buf.ReadInt();

            EndInit();
        }

        public static TalismanConfig DeserializeTalismanConfig(ByteBuf _buf)
        {
            return new TalismanConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 物品类型
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 装配位置
        /// </summary>
        public readonly int EquipPosition;
        /// <summary>
        /// c图标
        /// </summary>
        public readonly string Icon;
        /// <summary>
        /// 形状
        /// </summary>
        public readonly int Shape;
        /// <summary>
        /// 权重
        /// </summary>
        public readonly int Weight;
        /// <summary>
        /// 最大累加数量
        /// </summary>
        public readonly int MaxSumCount;
        /// <summary>
        /// s词条随机Id
        /// </summary>
        public readonly int Rarity;
        /// <summary>
        /// 售卖的基础价格
        /// </summary>
        public readonly int SellBasePrice;
        /// <summary>
        /// 灵气值
        /// </summary>
        public readonly int BaseScore;
        /// <summary>
        /// 图鉴状态
        /// </summary>
        public readonly int LabelType;
        /// <summary>
        /// 属性
        /// </summary>
        public readonly int Element;
        /// <summary>
        /// 火值
        /// </summary>
        public readonly int Huo;
        /// <summary>
        /// 水值
        /// </summary>
        public readonly int Shui;
        /// <summary>
        /// 冰值
        /// </summary>
        public readonly int Bing;
        /// <summary>
        /// 电值
        /// </summary>
        public readonly int Lei;
        /// <summary>
        /// 风值
        /// </summary>
        public readonly int Feng;
        /// <summary>
        /// 灵气加成
        /// </summary>
        public readonly int AddBuff;
        /// <summary>
        /// 灵气倍乘
        /// </summary>
        public readonly int TimeBuff;
        /// <summary>
        /// 灵气倍率
        /// </summary>
        public readonly int MultBuff;
    
        public const int __ID__ = 992980595;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Type:" + Type + ","
            + "EquipPosition:" + EquipPosition + ","
            + "Icon:" + Icon + ","
            + "Shape:" + Shape + ","
            + "Weight:" + Weight + ","
            + "MaxSumCount:" + MaxSumCount + ","
            + "Rarity:" + Rarity + ","
            + "SellBasePrice:" + SellBasePrice + ","
            + "BaseScore:" + BaseScore + ","
            + "LabelType:" + LabelType + ","
            + "Element:" + Element + ","
            + "Huo:" + Huo + ","
            + "Shui:" + Shui + ","
            + "Bing:" + Bing + ","
            + "Lei:" + Lei + ","
            + "Feng:" + Feng + ","
            + "AddBuff:" + AddBuff + ","
            + "TimeBuff:" + TimeBuff + ","
            + "MultBuff:" + MultBuff + ","
            + "}";
        }

        partial void EndRef();
    }

}

