
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class BattleLevelConfig : Luban.BeanBase
    {
        public BattleLevelConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); MonsterIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); MonsterIds.Add(_e0);}}
            Name = _buf.ReadString();
            {int n0 = _buf.ReadSize(); MiniEnterLevel = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); MiniEnterLevel.Add(_e0);}}
            RewardExp = _buf.ReadInt();

            EndInit();
        }

        public static BattleLevelConfig DeserializeBattleLevelConfig(ByteBuf _buf)
        {
            return new BattleLevelConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 怪物列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> MonsterIds;
        /// <summary>
        /// 关卡名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 准入等级范围
        /// </summary>
        public readonly System.Collections.Generic.List<int> MiniEnterLevel;
        /// <summary>
        /// 战斗胜利获取的经验值
        /// </summary>
        public readonly int RewardExp;
    
        public const int __ID__ = -1369519122;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MonsterIds:" + Luban.StringUtil.CollectionToString(MonsterIds) + ","
            + "Name:" + Name + ","
            + "MiniEnterLevel:" + Luban.StringUtil.CollectionToString(MiniEnterLevel) + ","
            + "RewardExp:" + RewardExp + ","
            + "}";
        }

        partial void EndRef();
    }

}

