
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class EntryRandomConfig : Luban.BeanBase
    {
        public EntryRandomConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            EntryRandMinCount = _buf.ReadInt();
            EntryRandMaxCount = _buf.ReadInt();
            SpecialEntryRandMinCount = _buf.ReadInt();
            SpecialEntryRandMaxCount = _buf.ReadInt();
            EntryLevel = _buf.ReadInt();
            SpecialEntryLevel = _buf.ReadInt();

            EndInit();
        }

        public static EntryRandomConfig DeserializeEntryRandomConfig(ByteBuf _buf)
        {
            return new EntryRandomConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 随机词条最小数量
        /// </summary>
        public readonly int EntryRandMinCount;
        /// <summary>
        /// 随机词条最大数量
        /// </summary>
        public readonly int EntryRandMaxCount;
        /// <summary>
        /// 随机特殊词条最小数量
        /// </summary>
        public readonly int SpecialEntryRandMinCount;
        /// <summary>
        /// 随机特殊词条最大数量
        /// </summary>
        public readonly int SpecialEntryRandMaxCount;
        /// <summary>
        /// 随机词条等级
        /// </summary>
        public readonly int EntryLevel;
        /// <summary>
        /// 随机特殊词条等级
        /// </summary>
        public readonly int SpecialEntryLevel;
    
        public const int __ID__ = 2142959447;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "EntryRandMinCount:" + EntryRandMinCount + ","
            + "EntryRandMaxCount:" + EntryRandMaxCount + ","
            + "SpecialEntryRandMinCount:" + SpecialEntryRandMinCount + ","
            + "SpecialEntryRandMaxCount:" + SpecialEntryRandMaxCount + ","
            + "EntryLevel:" + EntryLevel + ","
            + "SpecialEntryLevel:" + SpecialEntryLevel + ","
            + "}";
        }

        partial void EndRef();
    }

}

