
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class MapAIConfigCategory : Singleton<MapAIConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, MapAIConfig> _dataMap;
        private readonly List<MapAIConfig> _dataList;
        
        public MapAIConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MapAIConfig>();
            _dataList = new List<MapAIConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                MapAIConfig _v;
                _v = global::ET.MapAIConfig.DeserializeMapAIConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, MapAIConfig> GetAll() => _dataMap;
        public Dictionary<int, MapAIConfig> DataMap => _dataMap;
        public List<MapAIConfig> DataList => _dataList;

        public MapAIConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public MapAIConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

