
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class TalismanConfigCategory : Singleton<TalismanConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, TalismanConfig> _dataMap;
        private readonly List<TalismanConfig> _dataList;
        
        public TalismanConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TalismanConfig>();
            _dataList = new List<TalismanConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                TalismanConfig _v;
                _v = global::ET.TalismanConfig.DeserializeTalismanConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, TalismanConfig> GetAll() => _dataMap;
        public Dictionary<int, TalismanConfig> DataMap => _dataMap;
        public List<TalismanConfig> DataList => _dataList;

        public TalismanConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public TalismanConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

