
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            MaxHP = _buf.ReadInt();
            DamageValue = _buf.ReadInt();
            PrefabName = _buf.ReadString();
            MaxBagCapacity = _buf.ReadInt();
            Level = _buf.ReadInt();
            Exp = _buf.ReadInt();
            Gold = _buf.ReadInt();
            Diamond = _buf.ReadInt();
            ItemId = _buf.ReadInt();
            Energy = _buf.ReadInt();
            PrefabType = _buf.ReadInt();
            ItemConfigId = _buf.ReadInt();
            ForgeNum = _buf.ReadInt();

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 最大生命值
        /// </summary>
        public readonly int MaxHP;
        /// <summary>
        /// 攻击伤害值
        /// </summary>
        public readonly int DamageValue;
        /// <summary>
        /// 预设物名
        /// </summary>
        public readonly string PrefabName;
        /// <summary>
        /// 背包最大负重
        /// </summary>
        public readonly int MaxBagCapacity;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 经验
        /// </summary>
        public readonly int Exp;
        /// <summary>
        /// 金钱
        /// </summary>
        public readonly int Gold;
        /// <summary>
        /// 钻石
        /// </summary>
        public readonly int Diamond;
        /// <summary>
        /// 配套物
        /// </summary>
        public readonly int ItemId;
        /// <summary>
        /// 能量
        /// </summary>
        public readonly int Energy;
        /// <summary>
        /// 预制体类型
        /// </summary>
        public readonly int PrefabType;
        /// <summary>
        /// 物品表ID
        /// </summary>
        public readonly int ItemConfigId;
        /// <summary>
        /// 合成台格子数
        /// </summary>
        public readonly int ForgeNum;
    
        public const int __ID__ = -568528378;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "MaxHP:" + MaxHP + ","
            + "DamageValue:" + DamageValue + ","
            + "PrefabName:" + PrefabName + ","
            + "MaxBagCapacity:" + MaxBagCapacity + ","
            + "Level:" + Level + ","
            + "Exp:" + Exp + ","
            + "Gold:" + Gold + ","
            + "Diamond:" + Diamond + ","
            + "ItemId:" + ItemId + ","
            + "Energy:" + Energy + ","
            + "PrefabType:" + PrefabType + ","
            + "ItemConfigId:" + ItemConfigId + ","
            + "forgeNum:" + ForgeNum + ","
            + "}";
        }

        partial void EndRef();
    }

}

